using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eventomatic_DB
{
    /// <summary>
    /// Controller class for FB_Users_Sellers
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class FbUsersSellerController
    {
        // Preload our schema..
        FbUsersSeller thisSchemaLoad = new FbUsersSeller();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public FbUsersSellerCollection FetchAll()
        {
            FbUsersSellerCollection coll = new FbUsersSellerCollection();
            Query qry = new Query(FbUsersSeller.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public FbUsersSellerCollection FetchByID(object FbUsersSellersKey)
        {
            FbUsersSellerCollection coll = new FbUsersSellerCollection().Where("FB_Users_Sellers_Key", FbUsersSellersKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public FbUsersSellerCollection FetchByQuery(Query qry)
        {
            FbUsersSellerCollection coll = new FbUsersSellerCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object FbUsersSellersKey)
        {
            return (FbUsersSeller.Delete(FbUsersSellersKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object FbUsersSellersKey)
        {
            return (FbUsersSeller.Destroy(FbUsersSellersKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(long FBid,int? EventKey,int? TicketKey,bool? ShowGoals,decimal? GoalAmount,string FullName,string Email,bool? StreamStories,string AccessToken)
	    {
		    FbUsersSeller item = new FbUsersSeller();
		    
            item.FBid = FBid;
            
            item.EventKey = EventKey;
            
            item.TicketKey = TicketKey;
            
            item.ShowGoals = ShowGoals;
            
            item.GoalAmount = GoalAmount;
            
            item.FullName = FullName;
            
            item.Email = Email;
            
            item.StreamStories = StreamStories;
            
            item.AccessToken = AccessToken;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int FbUsersSellersKey,long FBid,int? EventKey,int? TicketKey,bool? ShowGoals,decimal? GoalAmount,string FullName,string Email,bool? StreamStories,string AccessToken)
	    {
		    FbUsersSeller item = new FbUsersSeller();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.FbUsersSellersKey = FbUsersSellersKey;
				
			item.FBid = FBid;
				
			item.EventKey = EventKey;
				
			item.TicketKey = TicketKey;
				
			item.ShowGoals = ShowGoals;
				
			item.GoalAmount = GoalAmount;
				
			item.FullName = FullName;
				
			item.Email = Email;
				
			item.StreamStories = StreamStories;
				
			item.AccessToken = AccessToken;
				
	        item.Save(UserName);
	    }
    }
}
