using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eventomatic_DB
{
	/// <summary>
	/// Strongly-typed collection for the FbUsersResource class.
	/// </summary>
    [Serializable]
	public partial class FbUsersResourceCollection : ActiveList<FbUsersResource, FbUsersResourceCollection>
	{	   
		public FbUsersResourceCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>FbUsersResourceCollection</returns>
		public FbUsersResourceCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                FbUsersResource o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the FB_Users_Resource table.
	/// </summary>
	[Serializable]
	public partial class FbUsersResource : ActiveRecord<FbUsersResource>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public FbUsersResource()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public FbUsersResource(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public FbUsersResource(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public FbUsersResource(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("FB_Users_Resource", TableType.Table, DataService.GetInstance("Eventomatic"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarFbUsersResourceKey = new TableSchema.TableColumn(schema);
				colvarFbUsersResourceKey.ColumnName = "FB_Users_Resource_Key";
				colvarFbUsersResourceKey.DataType = DbType.Int32;
				colvarFbUsersResourceKey.MaxLength = 0;
				colvarFbUsersResourceKey.AutoIncrement = true;
				colvarFbUsersResourceKey.IsNullable = false;
				colvarFbUsersResourceKey.IsPrimaryKey = true;
				colvarFbUsersResourceKey.IsForeignKey = false;
				colvarFbUsersResourceKey.IsReadOnly = false;
				colvarFbUsersResourceKey.DefaultSetting = @"";
				colvarFbUsersResourceKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarFbUsersResourceKey);
				
				TableSchema.TableColumn colvarFBid = new TableSchema.TableColumn(schema);
				colvarFBid.ColumnName = "FBid";
				colvarFBid.DataType = DbType.Int64;
				colvarFBid.MaxLength = 0;
				colvarFBid.AutoIncrement = false;
				colvarFBid.IsNullable = false;
				colvarFBid.IsPrimaryKey = false;
				colvarFBid.IsForeignKey = true;
				colvarFBid.IsReadOnly = false;
				colvarFBid.DefaultSetting = @"";
				
					colvarFBid.ForeignKeyTableName = "FB_Users";
				schema.Columns.Add(colvarFBid);
				
				TableSchema.TableColumn colvarResourceKey = new TableSchema.TableColumn(schema);
				colvarResourceKey.ColumnName = "Resource_Key";
				colvarResourceKey.DataType = DbType.Int32;
				colvarResourceKey.MaxLength = 0;
				colvarResourceKey.AutoIncrement = false;
				colvarResourceKey.IsNullable = false;
				colvarResourceKey.IsPrimaryKey = false;
				colvarResourceKey.IsForeignKey = true;
				colvarResourceKey.IsReadOnly = false;
				colvarResourceKey.DefaultSetting = @"";
				
					colvarResourceKey.ForeignKeyTableName = "Resource";
				schema.Columns.Add(colvarResourceKey);
				
				TableSchema.TableColumn colvarLastChange = new TableSchema.TableColumn(schema);
				colvarLastChange.ColumnName = "Last_Change";
				colvarLastChange.DataType = DbType.DateTime;
				colvarLastChange.MaxLength = 0;
				colvarLastChange.AutoIncrement = false;
				colvarLastChange.IsNullable = false;
				colvarLastChange.IsPrimaryKey = false;
				colvarLastChange.IsForeignKey = false;
				colvarLastChange.IsReadOnly = false;
				colvarLastChange.DefaultSetting = @"";
				colvarLastChange.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLastChange);
				
				TableSchema.TableColumn colvarSmsNumber = new TableSchema.TableColumn(schema);
				colvarSmsNumber.ColumnName = "Sms_Number";
				colvarSmsNumber.DataType = DbType.String;
				colvarSmsNumber.MaxLength = 20;
				colvarSmsNumber.AutoIncrement = false;
				colvarSmsNumber.IsNullable = true;
				colvarSmsNumber.IsPrimaryKey = false;
				colvarSmsNumber.IsForeignKey = false;
				colvarSmsNumber.IsReadOnly = false;
				colvarSmsNumber.DefaultSetting = @"";
				colvarSmsNumber.ForeignKeyTableName = "";
				schema.Columns.Add(colvarSmsNumber);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Eventomatic"].AddSchema("FB_Users_Resource",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("FbUsersResourceKey")]
		[Bindable(true)]
		public int FbUsersResourceKey 
		{
			get { return GetColumnValue<int>(Columns.FbUsersResourceKey); }
			set { SetColumnValue(Columns.FbUsersResourceKey, value); }
		}
		  
		[XmlAttribute("FBid")]
		[Bindable(true)]
		public long FBid 
		{
			get { return GetColumnValue<long>(Columns.FBid); }
			set { SetColumnValue(Columns.FBid, value); }
		}
		  
		[XmlAttribute("ResourceKey")]
		[Bindable(true)]
		public int ResourceKey 
		{
			get { return GetColumnValue<int>(Columns.ResourceKey); }
			set { SetColumnValue(Columns.ResourceKey, value); }
		}
		  
		[XmlAttribute("LastChange")]
		[Bindable(true)]
		public DateTime LastChange 
		{
			get { return GetColumnValue<DateTime>(Columns.LastChange); }
			set { SetColumnValue(Columns.LastChange, value); }
		}
		  
		[XmlAttribute("SmsNumber")]
		[Bindable(true)]
		public string SmsNumber 
		{
			get { return GetColumnValue<string>(Columns.SmsNumber); }
			set { SetColumnValue(Columns.SmsNumber, value); }
		}
		
		#endregion
		
		
			
		
		#region ForeignKey Properties
		
		/// <summary>
		/// Returns a FbUser ActiveRecord object related to this FbUsersResource
		/// 
		/// </summary>
		public Eventomatic_DB.FbUser FbUser
		{
			get { return Eventomatic_DB.FbUser.FetchByID(this.FBid); }
			set { SetColumnValue("FBid", value.FBid); }
		}
		
		
		/// <summary>
		/// Returns a Resource ActiveRecord object related to this FbUsersResource
		/// 
		/// </summary>
		public Eventomatic_DB.Resource Resource
		{
			get { return Eventomatic_DB.Resource.FetchByID(this.ResourceKey); }
			set { SetColumnValue("Resource_Key", value.ResourceKey); }
		}
		
		
		#endregion
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(long varFBid,int varResourceKey,DateTime varLastChange,string varSmsNumber)
		{
			FbUsersResource item = new FbUsersResource();
			
			item.FBid = varFBid;
			
			item.ResourceKey = varResourceKey;
			
			item.LastChange = varLastChange;
			
			item.SmsNumber = varSmsNumber;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varFbUsersResourceKey,long varFBid,int varResourceKey,DateTime varLastChange,string varSmsNumber)
		{
			FbUsersResource item = new FbUsersResource();
			
				item.FbUsersResourceKey = varFbUsersResourceKey;
			
				item.FBid = varFBid;
			
				item.ResourceKey = varResourceKey;
			
				item.LastChange = varLastChange;
			
				item.SmsNumber = varSmsNumber;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn FbUsersResourceKeyColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn FBidColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn ResourceKeyColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        public static TableSchema.TableColumn LastChangeColumn
        {
            get { return Schema.Columns[3]; }
        }
        
        
        
        public static TableSchema.TableColumn SmsNumberColumn
        {
            get { return Schema.Columns[4]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string FbUsersResourceKey = @"FB_Users_Resource_Key";
			 public static string FBid = @"FBid";
			 public static string ResourceKey = @"Resource_Key";
			 public static string LastChange = @"Last_Change";
			 public static string SmsNumber = @"Sms_Number";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
