using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eventomatic_DB
{
    /// <summary>
    /// Controller class for Log_Activities_Possibilities
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class LogActivitiesPossibilityController
    {
        // Preload our schema..
        LogActivitiesPossibility thisSchemaLoad = new LogActivitiesPossibility();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public LogActivitiesPossibilityCollection FetchAll()
        {
            LogActivitiesPossibilityCollection coll = new LogActivitiesPossibilityCollection();
            Query qry = new Query(LogActivitiesPossibility.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public LogActivitiesPossibilityCollection FetchByID(object LogActivitiesPossibilitiesKey)
        {
            LogActivitiesPossibilityCollection coll = new LogActivitiesPossibilityCollection().Where("Log_Activities_Possibilities_Key", LogActivitiesPossibilitiesKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public LogActivitiesPossibilityCollection FetchByQuery(Query qry)
        {
            LogActivitiesPossibilityCollection coll = new LogActivitiesPossibilityCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object LogActivitiesPossibilitiesKey)
        {
            return (LogActivitiesPossibility.Delete(LogActivitiesPossibilitiesKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object LogActivitiesPossibilitiesKey)
        {
            return (LogActivitiesPossibility.Destroy(LogActivitiesPossibilitiesKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(int LogActivitiesPossibilitiesKey,string Activity)
	    {
		    LogActivitiesPossibility item = new LogActivitiesPossibility();
		    
            item.LogActivitiesPossibilitiesKey = LogActivitiesPossibilitiesKey;
            
            item.Activity = Activity;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int LogActivitiesPossibilitiesKey,string Activity)
	    {
		    LogActivitiesPossibility item = new LogActivitiesPossibility();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.LogActivitiesPossibilitiesKey = LogActivitiesPossibilitiesKey;
				
			item.Activity = Activity;
				
	        item.Save(UserName);
	    }
    }
}
