using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eventomatic_DB
{
    /// <summary>
    /// Controller class for Test
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TestController
    {
        // Preload our schema..
        Test thisSchemaLoad = new Test();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TestCollection FetchAll()
        {
            TestCollection coll = new TestCollection();
            Query qry = new Query(Test.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TestCollection FetchByID(object TestKey)
        {
            TestCollection coll = new TestCollection().Where("Test_Key", TestKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TestCollection FetchByQuery(Query qry)
        {
            TestCollection coll = new TestCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object TestKey)
        {
            return (Test.Delete(TestKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object TestKey)
        {
            return (Test.Destroy(TestKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string TestText,DateTime? TestUpdate)
	    {
		    Test item = new Test();
		    
            item.TestText = TestText;
            
            item.TestUpdate = TestUpdate;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int TestKey,string TestText,DateTime? TestUpdate)
	    {
		    Test item = new Test();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.TestKey = TestKey;
				
			item.TestText = TestText;
				
			item.TestUpdate = TestUpdate;
				
	        item.Save(UserName);
	    }
    }
}
