using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eventomatic_DB
{
    /// <summary>
    /// Controller class for Transaction_Errors
    /// </summary>
    [System.ComponentModel.DataObject]
    public partial class TransactionErrorController
    {
        // Preload our schema..
        TransactionError thisSchemaLoad = new TransactionError();
        private string userName = String.Empty;
        protected string UserName
        {
            get
            {
				if (userName.Length == 0) 
				{
    				if (System.Web.HttpContext.Current != null)
    				{
						userName=System.Web.HttpContext.Current.User.Identity.Name;
					}
					else
					{
						userName=System.Threading.Thread.CurrentPrincipal.Identity.Name;
					}
				}
				return userName;
            }
        }
        [DataObjectMethod(DataObjectMethodType.Select, true)]
        public TransactionErrorCollection FetchAll()
        {
            TransactionErrorCollection coll = new TransactionErrorCollection();
            Query qry = new Query(TransactionError.Schema);
            coll.LoadAndCloseReader(qry.ExecuteReader());
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Select, false)]
        public TransactionErrorCollection FetchByID(object TransactionErrorsKey)
        {
            TransactionErrorCollection coll = new TransactionErrorCollection().Where("Transaction_Errors_Key", TransactionErrorsKey).Load();
            return coll;
        }
		
		[DataObjectMethod(DataObjectMethodType.Select, false)]
        public TransactionErrorCollection FetchByQuery(Query qry)
        {
            TransactionErrorCollection coll = new TransactionErrorCollection();
            coll.LoadAndCloseReader(qry.ExecuteReader()); 
            return coll;
        }
        [DataObjectMethod(DataObjectMethodType.Delete, true)]
        public bool Delete(object TransactionErrorsKey)
        {
            return (TransactionError.Delete(TransactionErrorsKey) == 1);
        }
        [DataObjectMethod(DataObjectMethodType.Delete, false)]
        public bool Destroy(object TransactionErrorsKey)
        {
            return (TransactionError.Destroy(TransactionErrorsKey) == 1);
        }
        
        
    	
	    /// <summary>
	    /// Inserts a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Insert, true)]
	    public void Insert(string TransactionErrorsLog,DateTime? LastUpdated)
	    {
		    TransactionError item = new TransactionError();
		    
            item.TransactionErrorsLog = TransactionErrorsLog;
            
            item.LastUpdated = LastUpdated;
            
	    
		    item.Save(UserName);
	    }
    	
	    /// <summary>
	    /// Updates a record, can be used with the Object Data Source
	    /// </summary>
        [DataObjectMethod(DataObjectMethodType.Update, true)]
	    public void Update(int TransactionErrorsKey,string TransactionErrorsLog,DateTime? LastUpdated)
	    {
		    TransactionError item = new TransactionError();
	        item.MarkOld();
	        item.IsLoaded = true;
		    
			item.TransactionErrorsKey = TransactionErrorsKey;
				
			item.TransactionErrorsLog = TransactionErrorsLog;
				
			item.LastUpdated = LastUpdated;
				
	        item.Save(UserName);
	    }
    }
}
