using System; 
using System.Text; 
using System.Data;
using System.Data.SqlClient;
using System.Data.Common;
using System.Collections;
using System.Collections.Generic;
using System.ComponentModel;
using System.Configuration; 
using System.Xml; 
using System.Xml.Serialization;
using SubSonic; 
using SubSonic.Utilities;
// <auto-generated />
namespace Eventomatic_DB
{
	/// <summary>
	/// Strongly-typed collection for the TransactionError class.
	/// </summary>
    [Serializable]
	public partial class TransactionErrorCollection : ActiveList<TransactionError, TransactionErrorCollection>
	{	   
		public TransactionErrorCollection() {}
        
        /// <summary>
		/// Filters an existing collection based on the set criteria. This is an in-memory filter
		/// Thanks to developingchris for this!
        /// </summary>
        /// <returns>TransactionErrorCollection</returns>
		public TransactionErrorCollection Filter()
        {
            for (int i = this.Count - 1; i > -1; i--)
            {
                TransactionError o = this[i];
                foreach (SubSonic.Where w in this.wheres)
                {
                    bool remove = false;
                    System.Reflection.PropertyInfo pi = o.GetType().GetProperty(w.ColumnName);
                    if (pi.CanRead)
                    {
                        object val = pi.GetValue(o, null);
                        switch (w.Comparison)
                        {
                            case SubSonic.Comparison.Equals:
                                if (!val.Equals(w.ParameterValue))
                                {
                                    remove = true;
                                }
                                break;
                        }
                    }
                    if (remove)
                    {
                        this.Remove(o);
                        break;
                    }
                }
            }
            return this;
        }
		
		
	}
	/// <summary>
	/// This is an ActiveRecord class which wraps the Transaction_Errors table.
	/// </summary>
	[Serializable]
	public partial class TransactionError : ActiveRecord<TransactionError>, IActiveRecord
	{
		#region .ctors and Default Settings
		
		public TransactionError()
		{
		  SetSQLProps();
		  InitSetDefaults();
		  MarkNew();
		}
		
		private void InitSetDefaults() { SetDefaults(); }
		
		public TransactionError(bool useDatabaseDefaults)
		{
			SetSQLProps();
			if(useDatabaseDefaults)
				ForceDefaults();
			MarkNew();
		}
        
		public TransactionError(object keyID)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByKey(keyID);
		}
		 
		public TransactionError(string columnName, object columnValue)
		{
			SetSQLProps();
			InitSetDefaults();
			LoadByParam(columnName,columnValue);
		}
		
		protected static void SetSQLProps() { GetTableSchema(); }
		
		#endregion
		
		#region Schema and Query Accessor	
		public static Query CreateQuery() { return new Query(Schema); }
		public static TableSchema.Table Schema
		{
			get
			{
				if (BaseSchema == null)
					SetSQLProps();
				return BaseSchema;
			}
		}
		
		private static void GetTableSchema() 
		{
			if(!IsSchemaInitialized)
			{
				//Schema declaration
				TableSchema.Table schema = new TableSchema.Table("Transaction_Errors", TableType.Table, DataService.GetInstance("Eventomatic"));
				schema.Columns = new TableSchema.TableColumnCollection();
				schema.SchemaName = @"dbo";
				//columns
				
				TableSchema.TableColumn colvarTransactionErrorsKey = new TableSchema.TableColumn(schema);
				colvarTransactionErrorsKey.ColumnName = "Transaction_Errors_Key";
				colvarTransactionErrorsKey.DataType = DbType.Int32;
				colvarTransactionErrorsKey.MaxLength = 0;
				colvarTransactionErrorsKey.AutoIncrement = true;
				colvarTransactionErrorsKey.IsNullable = false;
				colvarTransactionErrorsKey.IsPrimaryKey = true;
				colvarTransactionErrorsKey.IsForeignKey = false;
				colvarTransactionErrorsKey.IsReadOnly = false;
				colvarTransactionErrorsKey.DefaultSetting = @"";
				colvarTransactionErrorsKey.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTransactionErrorsKey);
				
				TableSchema.TableColumn colvarTransactionErrorsLog = new TableSchema.TableColumn(schema);
				colvarTransactionErrorsLog.ColumnName = "Transaction_Errors_Log";
				colvarTransactionErrorsLog.DataType = DbType.AnsiString;
				colvarTransactionErrorsLog.MaxLength = 2147483647;
				colvarTransactionErrorsLog.AutoIncrement = false;
				colvarTransactionErrorsLog.IsNullable = true;
				colvarTransactionErrorsLog.IsPrimaryKey = false;
				colvarTransactionErrorsLog.IsForeignKey = false;
				colvarTransactionErrorsLog.IsReadOnly = false;
				colvarTransactionErrorsLog.DefaultSetting = @"";
				colvarTransactionErrorsLog.ForeignKeyTableName = "";
				schema.Columns.Add(colvarTransactionErrorsLog);
				
				TableSchema.TableColumn colvarLastUpdated = new TableSchema.TableColumn(schema);
				colvarLastUpdated.ColumnName = "Last_Updated";
				colvarLastUpdated.DataType = DbType.DateTime;
				colvarLastUpdated.MaxLength = 0;
				colvarLastUpdated.AutoIncrement = false;
				colvarLastUpdated.IsNullable = true;
				colvarLastUpdated.IsPrimaryKey = false;
				colvarLastUpdated.IsForeignKey = false;
				colvarLastUpdated.IsReadOnly = false;
				colvarLastUpdated.DefaultSetting = @"";
				colvarLastUpdated.ForeignKeyTableName = "";
				schema.Columns.Add(colvarLastUpdated);
				
				BaseSchema = schema;
				//add this schema to the provider
				//so we can query it later
				DataService.Providers["Eventomatic"].AddSchema("Transaction_Errors",schema);
			}
		}
		#endregion
		
		#region Props
		  
		[XmlAttribute("TransactionErrorsKey")]
		[Bindable(true)]
		public int TransactionErrorsKey 
		{
			get { return GetColumnValue<int>(Columns.TransactionErrorsKey); }
			set { SetColumnValue(Columns.TransactionErrorsKey, value); }
		}
		  
		[XmlAttribute("TransactionErrorsLog")]
		[Bindable(true)]
		public string TransactionErrorsLog 
		{
			get { return GetColumnValue<string>(Columns.TransactionErrorsLog); }
			set { SetColumnValue(Columns.TransactionErrorsLog, value); }
		}
		  
		[XmlAttribute("LastUpdated")]
		[Bindable(true)]
		public DateTime? LastUpdated 
		{
			get { return GetColumnValue<DateTime?>(Columns.LastUpdated); }
			set { SetColumnValue(Columns.LastUpdated, value); }
		}
		
		#endregion
		
		
			
		
		//no foreign key tables defined (0)
		
		
		
		//no ManyToMany tables defined (0)
		
        
        
		#region ObjectDataSource support
		
		
		/// <summary>
		/// Inserts a record, can be used with the Object Data Source
		/// </summary>
		public static void Insert(string varTransactionErrorsLog,DateTime? varLastUpdated)
		{
			TransactionError item = new TransactionError();
			
			item.TransactionErrorsLog = varTransactionErrorsLog;
			
			item.LastUpdated = varLastUpdated;
			
		
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		
		/// <summary>
		/// Updates a record, can be used with the Object Data Source
		/// </summary>
		public static void Update(int varTransactionErrorsKey,string varTransactionErrorsLog,DateTime? varLastUpdated)
		{
			TransactionError item = new TransactionError();
			
				item.TransactionErrorsKey = varTransactionErrorsKey;
			
				item.TransactionErrorsLog = varTransactionErrorsLog;
			
				item.LastUpdated = varLastUpdated;
			
			item.IsNew = false;
			if (System.Web.HttpContext.Current != null)
				item.Save(System.Web.HttpContext.Current.User.Identity.Name);
			else
				item.Save(System.Threading.Thread.CurrentPrincipal.Identity.Name);
		}
		#endregion
        
        
        
        #region Typed Columns
        
        
        public static TableSchema.TableColumn TransactionErrorsKeyColumn
        {
            get { return Schema.Columns[0]; }
        }
        
        
        
        public static TableSchema.TableColumn TransactionErrorsLogColumn
        {
            get { return Schema.Columns[1]; }
        }
        
        
        
        public static TableSchema.TableColumn LastUpdatedColumn
        {
            get { return Schema.Columns[2]; }
        }
        
        
        
        #endregion
		#region Columns Struct
		public struct Columns
		{
			 public static string TransactionErrorsKey = @"Transaction_Errors_Key";
			 public static string TransactionErrorsLog = @"Transaction_Errors_Log";
			 public static string LastUpdated = @"Last_Updated";
						
		}
		#endregion
		
		#region Update PK Collections
		
        #endregion
    
        #region Deep Save
		
        #endregion
	}
}
